CREATE TABLE [dbo].[T_CallDetails] (
    [CallDetailId]                  BIGINT         IDENTITY (1, 1) NOT NULL,
    [AssignmentId]                  BIGINT         NULL,
    [UpdatedBy]                     VARCHAR (100)  NULL,
    [UpdatedByEmail]                VARCHAR (100)  NULL,
    [UpdatedByADID]                 VARCHAR (50)   NULL,
    [UpdatedOnUTC]                  DATETIME       NULL,
    [CallActionId]                  INT            NULL,
    [CustomerName]                  VARCHAR (200)  NULL,
    [CaseNumber]                    VARCHAR (50)   NULL,
    [UnitSlNo]                      VARCHAR (50)   NULL,
    [PassId]                        VARCHAR (50)   NULL,
    [TaskStartDateTimeIST]          DATETIME       NULL,
    [TaskEndDateTimeIST]            DATETIME       NULL,
    [CloserRemarks]                 NVARCHAR (MAX) NULL,
    [PartConsumptionTypeId]         INT            NULL,
    [SONo]                          VARCHAR (50)   NULL,
    [RequiredPart]                  NVARCHAR (MAX) NULL,
    [RequiredSparePartNo]           VARCHAR (50)   NULL,
    [RequiredPartName]              VARCHAR (100)  NULL,
    [FaultyPartCTNo]                VARCHAR (50)   NULL,
    [FailureId]                     VARCHAR (50)   NULL,
    [IssueDescription]              NVARCHAR (MAX) NULL,
    [TroubleshootingStep]           NVARCHAR (MAX) NULL,
    [FirstPartConsumptionTypeId]    INT            NULL,
    [FirstPartSONo]                 VARCHAR (50)   NULL,
    [FirstRequiredPartName]         VARCHAR (100)  NULL,
    [ReceivedPartConsumptionTypeId] INT            NULL,
    [ReceivedPartName]              VARCHAR (100)  NULL,
    PRIMARY KEY CLUSTERED ([CallDetailId] ASC)
);

