CREATE TABLE [dbo].[T_TicketDetails] (
    [CaseNumber]                   VARCHAR (50)    NOT NULL,
    [TicketId]                     BIGINT          NULL,
    [FromEmail]                    VARCHAR (100)   NULL,
    [ToEmail]                      VARCHAR (100)   NULL,
    [CaseSubject]                  NVARCHAR (500)  NULL,
    [WorkOrderNumber]              VARCHAR (50)    NULL,
    [ServiceAccount]               VARCHAR (100)   NULL,
    [ContactName]                  VARCHAR (100)   NULL,
    [ContactEmail]                 VARCHAR (100)   NULL,
    [ContactPhone]                 VARCHAR (100)   NULL,
    [ServiceDeliveryStreetAddress] NVARCHAR (200)  NULL,
    [ServiceDeliveryCity]          NVARCHAR (50)   NULL,
    [ServiceDeliveryCountry]       NVARCHAR (50)   NULL,
    [PostalCode]                   VARCHAR (50)    NULL,
    [SerialNumber]                 NVARCHAR (50)   NULL,
    [ProductName]                  NVARCHAR (100)  NULL,
    [ProductNumber]                VARCHAR (50)    NULL,
    [OTCCode]                      NVARCHAR (100)  NULL,
    [PartNumber]                   NVARCHAR (100)  NULL,
    [PartDescription]              NVARCHAR (1000) NULL,
    [EmailSubject]                 NVARCHAR (500)  NULL,
    [EmailDate]                    VARCHAR (50)    NULL,
    [CreatedOn]                    DATETIME        NULL,
    [PartNumber2]                  NVARCHAR (100)  NULL,
    [PartDescription2]             NVARCHAR (1000) NULL,
    [PartNumber3]                  NVARCHAR (100)  NULL,
    [PartDescription3]             NVARCHAR (1000) NULL,
    [TicketType]                   VARCHAR(10) NULL, 
    CONSTRAINT [PK_T_TicketDetails] PRIMARY KEY CLUSTERED ([CaseNumber] ASC)
);

